/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoumnsh;

import Opciones.Abonar;
import Opciones.Consultar;
import Opciones.Retirar;
import VerClientes.AltaClientes;
import VerClientes.BajaClientes;

/**
 *
 * @author glzgi
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMnBPrincipal = new javax.swing.JMenuBar();
        jMnuOpciones = new javax.swing.JMenu();
        jMntAbonar = new javax.swing.JMenuItem();
        jMntRetirar = new javax.swing.JMenuItem();
        jMntConsultar = new javax.swing.JMenuItem();
        jMnuReporte = new javax.swing.JMenu();
        jMnuVerCliente = new javax.swing.JMenu();
        jMntAltaCliente = new javax.swing.JMenuItem();
        jMntBajaCliente = new javax.swing.JMenuItem();
        jMntConsultarClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jMnuOpciones.setText("Opciones");

        jMntAbonar.setText("Abonar");
        jMntAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntAbonarActionPerformed(evt);
            }
        });
        jMnuOpciones.add(jMntAbonar);

        jMntRetirar.setText("Reitrar");
        jMntRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntRetirarActionPerformed(evt);
            }
        });
        jMnuOpciones.add(jMntRetirar);

        jMntConsultar.setText("Consultar");
        jMntConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntConsultarActionPerformed(evt);
            }
        });
        jMnuOpciones.add(jMntConsultar);

        jMnBPrincipal.add(jMnuOpciones);

        jMnuReporte.setText("Reporte");
        jMnBPrincipal.add(jMnuReporte);

        jMnuVerCliente.setText("Ver Clientes");

        jMntAltaCliente.setText("Alta");
        jMntAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntAltaClienteActionPerformed(evt);
            }
        });
        jMnuVerCliente.add(jMntAltaCliente);

        jMntBajaCliente.setText("Baja");
        jMntBajaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntBajaClienteActionPerformed(evt);
            }
        });
        jMnuVerCliente.add(jMntBajaCliente);

        jMntConsultarClientes.setText("Consultar");
        jMntConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMntConsultarClientesActionPerformed(evt);
            }
        });
        jMnuVerCliente.add(jMntConsultarClientes);

        jMnBPrincipal.add(jMnuVerCliente);

        setJMenuBar(jMnBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMntAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntAltaClienteActionPerformed
        // TODO add your handling code here:
        AltaClientes verFormulario = new AltaClientes ();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMntAltaClienteActionPerformed

    private void jMntConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntConsultarClientesActionPerformed
        // TODO add your handling code here:
        Consultar verFormulario = new Consultar ();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMntConsultarClientesActionPerformed

    private void jMntAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntAbonarActionPerformed
        // TODO add your handling code here:
        Abonar verFormulario = new Abonar ();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMntAbonarActionPerformed

    private void jMntRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntRetirarActionPerformed
        // TODO add your handling code here:
        Retirar verFormulario = new Retirar ();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMntRetirarActionPerformed

    private void jMntConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntConsultarActionPerformed
        // TODO add your handling code here:
        Consultar verFormulario = new Consultar ();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMntConsultarActionPerformed

    private void jMntBajaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMntBajaClienteActionPerformed
        // TODO add your handling code here:
        BajaClientes verFormulario = new BajaClientes ();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMntBajaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMnBPrincipal;
    private javax.swing.JMenuItem jMntAbonar;
    private javax.swing.JMenuItem jMntAltaCliente;
    private javax.swing.JMenuItem jMntBajaCliente;
    private javax.swing.JMenuItem jMntConsultar;
    private javax.swing.JMenuItem jMntConsultarClientes;
    private javax.swing.JMenuItem jMntRetirar;
    private javax.swing.JMenu jMnuOpciones;
    private javax.swing.JMenu jMnuReporte;
    private javax.swing.JMenu jMnuVerCliente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
