/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Opciones;
/**
 *
 * @author RONALDO
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlConsultar = new javax.swing.JPanel();
        jLblBuscar = new javax.swing.JLabel();
        jChcId = new javax.swing.JCheckBox();
        jChcNombre = new javax.swing.JCheckBox();
        jChcApellidoPaterno = new javax.swing.JCheckBox();
        jTxtId1 = new javax.swing.JTextField();
        jTxtNombre1 = new javax.swing.JTextField();
        jTxtApellidoPaterno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCliente = new javax.swing.JTable();
        jBtnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlConsultar.setBackground(new java.awt.Color(0, 51, 51));
        jPnlConsultar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLblBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLblBuscar.setText("Buscar");

        jChcId.setBackground(new java.awt.Color(0, 51, 51));
        jChcId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChcId.setForeground(new java.awt.Color(255, 255, 255));
        jChcId.setText("ID");

        jChcNombre.setBackground(new java.awt.Color(0, 51, 51));
        jChcNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChcNombre.setForeground(new java.awt.Color(255, 255, 255));
        jChcNombre.setText("Nombre");

        jChcApellidoPaterno.setBackground(new java.awt.Color(0, 51, 51));
        jChcApellidoPaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jChcApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        jChcApellidoPaterno.setText("Apellido Paterno");

        jTblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblCliente);

        jBtnBuscar.setBackground(new java.awt.Color(0, 51, 51));
        jBtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnBuscar.setForeground(new java.awt.Color(0, 51, 51));
        jBtnBuscar.setText("Buscar");

        javax.swing.GroupLayout jPnlConsultarLayout = new javax.swing.GroupLayout(jPnlConsultar);
        jPnlConsultar.setLayout(jPnlConsultarLayout);
        jPnlConsultarLayout.setHorizontalGroup(
            jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlConsultarLayout.createSequentialGroup()
                .addGroup(jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlConsultarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlConsultarLayout.createSequentialGroup()
                                .addComponent(jChcId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlConsultarLayout.createSequentialGroup()
                                .addComponent(jChcApellidoPaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlConsultarLayout.createSequentialGroup()
                                .addComponent(jChcNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLblBuscar)))
                    .addGroup(jPnlConsultarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlConsultarLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jBtnBuscar)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPnlConsultarLayout.setVerticalGroup(
            jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlConsultarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLblBuscar)
                .addGap(18, 18, 18)
                .addGroup(jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChcId)
                    .addComponent(jTxtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChcNombre)
                    .addComponent(jTxtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChcApellidoPaterno)
                    .addComponent(jTxtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jBtnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JCheckBox jChcApellidoPaterno;
    private javax.swing.JCheckBox jChcId;
    private javax.swing.JCheckBox jChcNombre;
    private javax.swing.JLabel jLblBuscar;
    private javax.swing.JPanel jPnlConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCliente;
    private javax.swing.JTextField jTxtApellidoPaterno;
    private javax.swing.JTextField jTxtId1;
    private javax.swing.JTextField jTxtNombre1;
    // End of variables declaration//GEN-END:variables
}
