/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Opciones;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import proyectoumnsh.Menu;

/**
 *
 * @author RONALDO
 */
public class Retirar extends javax.swing.JFrame {
    private ResultSet consulta; //variable que guardará el resultado de la consulta
    private PreparedStatement pst; //variable que ejecutará las sentencias a la B.D.
    private Connection conexion=null; //variable que llevará a cabo la conexión a la B.D.
    private String genero; //variable que almacenará el caracter del género del alumno
    private String Monto, Motivo;
    /**
     * Creates new form Retirar
     */
    public Retirar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlRetirar = new javax.swing.JPanel();
        jLblMonto = new javax.swing.JLabel();
        jLblMotivo = new javax.swing.JLabel();
        jTxtMonto = new javax.swing.JTextField();
        jTxtMotivo = new javax.swing.JTextField();
        jBntAceptar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlRetirar.setBackground(new java.awt.Color(0, 51, 51));
        jPnlRetirar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Retirar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLblMonto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblMonto.setForeground(new java.awt.Color(255, 255, 255));
        jLblMonto.setText("Monto:");

        jLblMotivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblMotivo.setForeground(new java.awt.Color(255, 255, 255));
        jLblMotivo.setText("Motivo:");

        jBntAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntAceptar.setForeground(new java.awt.Color(0, 51, 51));
        jBntAceptar.setText("Aceptar");
        jBntAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBntAceptarMouseClicked(evt);
            }
        });
        jBntAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlRetirarLayout = new javax.swing.GroupLayout(jPnlRetirar);
        jPnlRetirar.setLayout(jPnlRetirarLayout);
        jPnlRetirarLayout.setHorizontalGroup(
            jPnlRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRetirarLayout.createSequentialGroup()
                .addGroup(jPnlRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlRetirarLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPnlRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlRetirarLayout.createSequentialGroup()
                                .addComponent(jLblMotivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlRetirarLayout.createSequentialGroup()
                                .addComponent(jLblMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPnlRetirarLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jBntAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPnlRetirarLayout.setVerticalGroup(
            jPnlRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRetirarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPnlRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMonto)
                    .addComponent(jTxtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPnlRetirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMotivo)
                    .addComponent(jTxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jBntAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ir a menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBntAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBntAceptarMouseClicked
 
    }//GEN-LAST:event_jBntAceptarMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    Menu verFormulario = new Menu();
        verFormulario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBntAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntAceptarActionPerformed
        Monto = jTxtMonto.getText();
        Motivo = jTxtMotivo.getText();
        
        if (Monto.isEmpty()) {
          JOptionPane.showMessageDialog(null, "Motivo esta vacio");
        }
        else{
            int input = JOptionPane.showConfirmDialog(null, "¿Estas seguro que quieres Retirar: "+Monto+" ?", "Confirmacion", JOptionPane.YES_NO_OPTION);
            
            System.out.println(input);
            
            if (input == 0) {
                        try
                   {      
                       int resultado;
                       String sql;

                       sql = "INSERT INTO `Movimientos` (`idMovimientos`, `idUsuarios`, `motivo`, `fecha`, `hora`, `cantidad`) "
                               + "VALUES "
                               + "(NULL, '2', '"+Motivo+"', CURRENT_DATE, CURRENT_TIME, '"+Monto+"')";
                       pst=conexion.prepareStatement(sql);

                     resultado=pst.executeUpdate();
                     if (resultado==1) 
                     {
                         JOptionPane.showMessageDialog(null,"El abono ha sido insertado correctamente");
                         jTxtMonto.setText(null);
                         jTxtMotivo.setText(null);
                     }

                     else
                     {
                         JOptionPane.showMessageDialog(null,"El abono No ha sido insertado"); 
                     }


                   }
                   catch(SQLException e)
                   {
                       JOptionPane.showMessageDialog(null, e.toString());  
                   }
            }
            
                if(input ==1 )
                   {
                     jTxtMonto.setText(null);
                     jTxtMotivo.setText(null);
                     jTxtMonto.requestFocus();
                     
                   }
               
        }
    }//GEN-LAST:event_jBntAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retirar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retirar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntAceptar;
    private javax.swing.JLabel jLblMonto;
    private javax.swing.JLabel jLblMotivo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPnlRetirar;
    private javax.swing.JTextField jTxtMonto;
    private javax.swing.JTextField jTxtMotivo;
    // End of variables declaration//GEN-END:variables
}
