/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Opciones;

import javax.swing.JOptionPane;

/**
 *
 * @author RONALDO
 */
public class VentanaAbonar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAbonar
     */
    public VentanaAbonar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlVentanaAbonar = new javax.swing.JPanel();
        jLblTexto = new javax.swing.JLabel();
        jBtnAceptar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPnlVentanaAbonar.setBackground(new java.awt.Color(0, 51, 51));
        jPnlVentanaAbonar.setForeground(new java.awt.Color(0, 51, 51));

        jLblTexto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblTexto.setForeground(new java.awt.Color(255, 255, 255));
        jLblTexto.setText("¿Esta seguro del abono del monto?");

        jBtnAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnAceptar.setForeground(new java.awt.Color(0, 51, 51));
        jBtnAceptar.setText("Aceptar");
        jBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAceptarActionPerformed(evt);
            }
        });

        jBtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(0, 51, 51));
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlVentanaAbonarLayout = new javax.swing.GroupLayout(jPnlVentanaAbonar);
        jPnlVentanaAbonar.setLayout(jPnlVentanaAbonarLayout);
        jPnlVentanaAbonarLayout.setHorizontalGroup(
            jPnlVentanaAbonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVentanaAbonarLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPnlVentanaAbonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlVentanaAbonarLayout.createSequentialGroup()
                        .addComponent(jBtnAceptar)
                        .addGap(77, 77, 77)
                        .addComponent(jBtnCancelar)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlVentanaAbonarLayout.createSequentialGroup()
                        .addComponent(jLblTexto)
                        .addGap(39, 39, 39))))
        );
        jPnlVentanaAbonarLayout.setVerticalGroup(
            jPnlVentanaAbonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlVentanaAbonarLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLblTexto)
                .addGap(46, 46, 46)
                .addGroup(jPnlVentanaAbonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAceptar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlVentanaAbonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlVentanaAbonar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCancelarMouseClicked
 Abonar abonar = new Abonar();
 abonar.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_jBtnCancelarMouseClicked

    private void jBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAceptarActionPerformed
     JOptionPane.showMessageDialog(null,"El monto ha sido abonado correctamente");
    }//GEN-LAST:event_jBtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAbonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAbonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAbonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAbonar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAbonar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JLabel jLblTexto;
    private javax.swing.JPanel jPnlVentanaAbonar;
    // End of variables declaration//GEN-END:variables
}
